version: "3"
services:
    dbtest:
        container_name: dbtest
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB}
            DATABASE_URL: ${DB_URL_TEST}
        ports:
            - "5432:5432"
        expose:
            - 5432
        networks:
            - puma-network-test
    # project-service-test:
    #     container_name: project-service-test
    #     environment:
    #         ENVIRONMENT: test
    #     build:
    #         context: ../${PROJECT_PATH}/
    #         dockerfile: dev.Dockerfile
    #     ports:
    #         - "3000:3000"
    #     expose:
    #         - 3000
    #     depends_on:
    #         - dbtest
    #     volumes:
    #         - ../${PROJECT_PATH}:/app
    #     networks:
    #         - puma-network-test
    #     command:
    #       [
    #           "./wait-for-it.sh",
    #           "dbtest:5432",
    #           "--",
    #           "npm",
    #           "run",
    #           "start-dev"
    #       ]
    # user-service-test:
    #     container_name: user-service-test
    #     environment:
    #         ENVIRONMENT: test
    #     build:
    #         context: ../${USER_PATH}/
    #         dockerfile: dev.Dockerfile
    #     ports:
    #         - "3001:3001"
    #     expose:
    #         - 3001
    #     depends_on:
    #         - dbtest
    #     volumes:
    #         - ../${USER_PATH}:/app
    #     networks:
    #         - puma-network-test
    #     command:
    #       [
    #           "./wait-for-it.sh",
    #           "dbtest:5432",
    #           "--",
    #           "npm",
    #           "run",
    #           "start-dev"
    #       ]
    api-gateway-test:
        container_name: api-gateway-test
        environment:
            ENVIRONMENT: test
        build:
            context: .
            dockerfile: dev.Dockerfile
        depends_on:
            # - user-service-test
            - dbtest
            # - project-service-test
        ports:
            - "3004:3004"
        expose:
            - 3004
        volumes:
            - ./:/app
        networks:
            - puma-network-test

    # frontend-test:
    #     container_name: frontend-test
    #     environment:
    #         ENVIRONMENT: test
    #     build:
    #         context: ../${FRONT_PATH}/puma
    #         dockerfile: dev.Dockerfile
    #     ports:
    #         - "8080:8080"
    #     volumes:
    #         - ../${FRONT_PATH}/puma:/app
    #         - /app/node_modules
    #     networks:
    #         - puma-network-test

networks:
    puma-network-test:
