module.exports = {
  success: {
    aluno: {
      name: 'Luis',
      email: 'luishptaira@gmail.com',
      password: '123',
      repeatPassword: '123',
      matricula: 170109208,
      type: 'Aluno',
      externalAgentType: '',
      cnpj: '',
      cep: '',
      companyName: '',
      socialReason: '',
      cpf: '',
    },
    professor: {
      name: 'Mister M',
      email: 'Mister M@gmail.com',
      password: '123',
      repeatPassword: '123',
      matricula: 198298376,
      type: 'Professor',
      externalAgentType: '',
      cnpj: '',
      cep: '',
      companyName: '',
      socialReason: '',
      cpf: '',
    },
    externalPhysical: {
      name: 'Vandor',
      email: 'vandoropadeiro@gmail.com',
      password: '123',
      repeatPassword: '123',
      matricula: '',
      type: 'Agente Externo',
      externalAgentType: 'Pessoa Fisica',
      cnpj: '',
      cep: '',
      companyName: '',
      socialReason: '',
      cpf: '12345678901',
    },
    externaljuridical: {
      name: 'Vandor',
      email: 'padariadovandor@gmail.com',
      password: '123',
      repeatPassword: '123',
      matricula: '',
      type: 'Agente Externo',
      externalAgentType: 'Pessoa Juridica',
      cnpj: '12345678901234',
      cep: '12345678',
      companyName: 'Padaria do Vandor',
      socialReason: 'Padaria',
      cpf: '',
    },
  },
  fail: {
    aluno: {
      name: 'Luis',
      email: 'luishptaira@gmail.com',
      password: '123',
      repeatPassword: '123',
      type: 'Aluno',
      externalAgentType: '',
      cnpj: '',
      cep: '',
      companyName: '',
      socialReason: '',
      cpf: '',
    },
    alunoLoginWithoutPassword: {
      email: 'luishptaira@gmail.com',
      password: '',
    },
    alunoLoginWithoutemail: {
      email: '',
      password: '123',
    },
    loginUnexistingUser: {
      email: '',
      password: '123',
    },
    professor: {
      name: 'Mister M',
      email: 'Mister M@gmail.com',
      repeatPassword: '123',
      matricula: 198298376,
      type: 'Professor',
      externalAgentType: '',
      cnpj: '',
      cep: '',
      companyName: '',
      socialReason: '',
      cpf: '',
    },
    externalPhysical: {
      name: 'Vandor',
      email: 'vandoropadeiro@gmail.com',
      password: '123',
      repeatPassword: '123',
      matricula: '',
      type: 'Agente Externo',
      externalAgentType: 'Pessoa Fisica',
      cnpj: '',
      cep: '',
      companyName: '',
      socialReason: '',
    },
    externaljuridical: {
      name: 'Vandor',
      email: 'padariadovandor@gmail.com',
      password: '123',
      repeatPassword: '123',
      matricula: '',
      type: 'Agente Externo',
      externalAgentType: 'Pessoa Juridica',
      cnpj: '12345678901234',
      cep: '12345678',
      socialReason: 'Padaria',
      cpf: '',
    },
  }
}