name: CI

on:
  push:
    branches: 
      - dev
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    env:
        USER_PATH: 2022-2-PUMA-UserService 
        PROJECT_PATH: 2022-2-PUMA-ProjectService
        DB_USER: pumaadmin
        DB_PASS: pumaadmin
        DB: puma
        DB_URL_TEST: postgres://pumaadmin:pumaadmin@127.17.0.1:5432/puma
        IP_ADDRESS: 127.17.0.1

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Run npm install
      run: npm install
    - name: Run Tests
      run: npm run test
