name: Generate Metrics Release

on: 
  workflow_dispatch:
  release:
    types: [published]
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  send-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      - name: Create Metrics SonarCloud
        run: python3 metrics/metrics_file.py ${{ github.event.repository.name }} ${{ steps.previoustag.outputs.tag }}

      - name: Commit Metrics SonarCloud File
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_USERNAME }}"
          git clone --single-branch --branch main "https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/fga-eps-mds/2023-1-PUMA-Doc" puma_docs_repo
          mkdir -p puma_docs_repo/analytics-raw-data
          cp -R fga-eps-mds*.json puma_docs_repo/analytics-raw-data
          cd puma_docs_repo
          git add .
          git commit -m "Gerando métricas SonarCloud - ${{ github.event.repository.name }} ${{ github.ref_name }}"
          git push
          echo "Metrics File Generated Successfully."
